# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [93]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
insurance_company = pd.read_csv(url)
insurance_company

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
insurance_company.columns = (
    insurance_company.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(insurance_company.columns.tolist())
insurance_company.columns

['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

Index(['customer', 'st', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', 'total_claim_amount'],
      dtype='str')

In [95]:
insurance_company = insurance_company.rename(columns={
    "st": "state"
})

print(insurance_company.columns.tolist())

['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [96]:
insurance_company["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

In [97]:
# There are similar categories that need to be normalized i found this way of doing it
insurance_company["gender"] = (
    insurance_company["gender"]
      .str.replace("Femal", "F", regex=False)
      .str.replace("female", "F", regex=False)
      .str.replace("Male", "M", regex=False)
      .str.replace("nan", "unknown", regex=False)
)
insurance_company["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [98]:
insurance_company["gender"] = (
    insurance_company["gender"]
      .str.replace("Femal", "F", regex=False)
      .str.replace("female", "F", regex=False)
      .str.replace("Male", "M", regex=False)
      .str.replace("nan", "unknown", regex=False)
)
insurance_company["gender"].unique()

<ArrowStringArray>
[nan, 'F', 'M']
Length: 3, dtype: str

In [99]:
insurance_company["state"].unique()

<ArrowStringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str

In [100]:
# Action: mapping values to a common category
states = pd.Series(["Washington", "Arizona", "Nevada", "California", "Oregon", "Cali", "AZ", "WA", "nan"])
states_map = {
    "Washington": "Washington",
    "Arizona": "Arizona",
    "Nevada": "Nevada",
    "California": "California",
    "Oregon": "Oregon",
    "Cali": "California",
    "AZ": "Arizona",
    "WA": "Washington",
    "nan": "unknown"
}
clean_states = states.map(states_map)
display(clean_states)

0    Washington
1       Arizona
2        Nevada
3    California
4        Oregon
5    California
6       Arizona
7    Washington
8       unknown
dtype: str

In [101]:
insurance_company["state_original"] = insurance_company["state"]
insurance_company["state"] = insurance_company["state"].map(states_map)
insurance_company.head(20)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state_original
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,Washington
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,Arizona
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,Nevada
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,California
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,Washington
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042,Oregon
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000,Oregon
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680,Arizona
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000,Oregon
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834,Oregon
10,SX51350,California,M,College,473899.20%,0.0,67.0,1/0/00,Personal Auto,Four-Door Car,482.400000,California
11,VQ65197,California,NaN,College,819719.71%,0.0,110.0,1/0/00,Personal Auto,SUV,528.000000,California
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737,California
13,SJ95423,Arizona,NaN,High School or Below,881901.89%,99845.0,110.0,1/1/00,Corporate Auto,SUV,528.000000,Arizona
14,IL66569,California,NaN,College,538443.17%,83689.0,70.0,1/2/00,Corporate Auto,Four-Door Car,307.139132,California
15,BW63560,Oregon,NaN,Bachelor,746313.94%,24599.0,64.0,1/1/00,Corporate Auto,Four-Door Car,42.920271,Oregon
16,FV94802,Nevada,NaN,High School or Below,256686.78%,25049.0,67.0,1/0/00,Personal Auto,Two-Door Car,454.245098,Nevada
17,OE15005,California,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031,Cali
18,WC83389,Oregon,NaN,College,571033.31%,51148.0,72.0,1/0/00,Personal Auto,Four-Door Car,308.981664,Oregon
19,FL50705,California,NaN,High School or Below,816261.71%,66140.0,101.0,1/0/00,Corporate Auto,Four-Door Car,484.800000,California

In [192]:
# removing the helper column after implementing the changes
insurance_company = insurance_company.drop(columns=["state_original"])

In [102]:
#inspecting the column
insurance_company["education"].unique()

<ArrowStringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str

In [103]:
# Action taken here: Normalizing also the similar categories in this column
insurance_company["education"] = (
    insurance_company["education"]
      .str.replace("Bachelors", "Bachelor", regex=False)
)
insurance_company["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [104]:
insurance_company["customer_lifetime_value"].unique()

<ArrowStringArray>
[          nan,  '697953.59%', '1288743.17%',  '764586.18%',  '536307.65%',
  '825629.78%',  '538089.86%',  '721610.03%', '2412750.40%',  '738817.81%',
 ...
  '943891.56%', '1050677.17%',  '421391.86%',  '477368.64%',  '544142.01%',
  '284226.69%',  '305955.03%', '2031499.76%',  '323912.47%',  '899704.02%']
Length: 1028, dtype: str

In [105]:
# Removing the "%"
insurance_company["customer_lifetime_value"] = (
    insurance_company["customer_lifetime_value"] 
      .str.replace("%", "", regex=False)
)
insurance_company["customer_lifetime_value"]

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: str

In [106]:
insurance_company["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

In [107]:
insurance_company["vehicle_class"] = (
    insurance_company["vehicle_class"]
      .str.replace(" ", "_", regex=False)
)
insurance_company["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door_Car',  'Two-Door_Car',           'SUV',    'Luxury_SUV',
    'Sports_Car',    'Luxury_Car',             nan]
Length: 7, dtype: str

In [146]:
insurance_company["vehicle_class"] = (
    insurance_company["vehicle_class"]
      .str.replace("Luxury_SUV", "Luxury", regex=False)
      .str.replace("Luxury_Car", "Luxury", regex=False)
      .str.replace("Sports_Car", "Luxury", regex=False)
)
insurance_company["vehicle_class"].unique()

<ArrowStringArray>
['Four-Door_Car', 'Two-Door_Car', 'SUV', 'Luxury']
Length: 4, dtype: str

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [109]:
insurance_company.dtypes

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
state_original                   str
dtype: object

In [110]:
insurance_company["customer_lifetime_value"] = pd.to_numeric(insurance_company["customer_lifetime_value"], errors="coerce")
insurance_company["customer_lifetime_value"]

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: float64

In [68]:
insurance_company["number_of_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [112]:
number_of_open_complaints = (
    insurance_company["number_of_open_complaints"]
    .astype("string")
    .str.split("/")
    .str[1]
)

number_of_open_complaints = pd.to_numeric(
    number_of_open_complaints,
    errors="coerce"
)
number_of_open_complaints.unique()

array([ 0.,  2.,  1.,  3.,  5.,  4., nan])

In [113]:
print(number_of_open_complaints.head(20))
print(number_of_open_complaints.dtype)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    2.0
13    1.0
14    2.0
15    1.0
16    0.0
17    0.0
18    0.0
19    0.0
Name: number_of_open_complaints, dtype: float64
float64

In [117]:
insurance_company["number_of_open_complaints"] = number_of_open_complaints
insurance_company["number_of_open_complaints"].head(20)

0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
12    2.0
13    1.0
14    2.0
15    1.0
16    0.0
17    0.0
18    0.0
19    0.0
Name: number_of_open_complaints, dtype: float64

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [118]:
display(insurance_company.isna().sum())

customer                     2937
state                        2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
state_original               2937
dtype: int64

In [123]:
# the number of missing values is too high so i will remove all rows which all values are empty
insurance_company = insurance_company.dropna(axis = 0, how = 'all')
display(insurance_company)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state_original
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door_Car,2.704934,Washington
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door_Car,1131.464935,Arizona
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door_Car,566.472247,Nevada
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344,California
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door_Car,17.269323,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03,38644.0,78.0,1.0,Personal Auto,Four-Door_Car,361.455219,Oregon
1067,VJ51327,California,F,High School or Below,2031499.76,63209.0,102.0,2.0,Personal Auto,SUV,207.320041,Cali
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door_Car,633.600000,Arizona
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,0.0,Special Auto,SUV,547.200000,California
1070,MY31220,California,F,College,899704.02,54230.0,112.0,0.0,Personal Auto,Two-Door_Car,537.600000,California

In [147]:
insurance_company.isna().sum()

customer                       0
state                          0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
state_original                 0
dtype: int64

In [155]:
# Decided to fill the 117 missing gender data with the mode
gender_mode = insurance_company["gender"].mode()
insurance_company["gender_filled"] = insurance_company["gender"].fillna(gender_mode)
print(gender_mode)
display(insurance_company[["gender", "gender_filled"]])

0    F
Name: gender, dtype: str

     gender gender_filled
0       NaN             F
1         F             F
2         F             F
3         M             M
4         M             M
...     ...           ...
1066      M             M
1067      F             F
1068      F             F
1069      F             F
1070      F             F

[1071 rows x 2 columns]

In [159]:
display(insurance_company[["gender", "gender_filled"]].isna().sum())

gender           117
gender_filled    116
dtype: int64

In [165]:
gender_mode = insurance_company["gender"].mode(dropna=True).iloc[0]

insurance_company["gender_filled"] = (
    insurance_company["gender"].fillna(gender_mode)
)
display(insurance_company[["gender", "gender_filled"]].isna().sum())
print("Mode used:", gender_mode)

gender           117
gender_filled      0
dtype: int64

Mode used: F

In [166]:
insurance_company["gender"] = insurance_company["gender_filled"]
insurance_company["gender"].isna().sum()

np.int64(0)

In [167]:
insurance_company = insurance_company.drop(columns=["gender_filled"])

In [176]:
# inspecting the 3 missing values in column "customer_lifetime_value" in a total of 1071 values. 
# My strategy may be to fill the missing values with the median but I want to check all the columns related with these missing values.

missing_clv_rows = insurance_company[insurance_company["customer_lifetime_value"].isna()]
display(missing_clv_rows)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state_original
0,RB50392,Washington,F,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door_Car,2.704934,Washington
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,0.0,Personal Auto,Four-Door_Car,41.122303,Washington
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,0.0,Personal Auto,Four-Door_Car,227.872071,Washington

In [178]:
# inspecting only numerical columns
display(
    insurance_company.loc[
        insurance_company["customer_lifetime_value"].isna(),
        [
            "customer_lifetime_value",
            "monthly_premium_auto",
            "income",
            "total_claim_amount",
            "number_of_open_complaints"
        ]
    ]
)

,customer_lifetime_value,monthly_premium_auto,income,total_claim_amount,number_of_open_complaints
0,NaN,1000.0,0.0,2.704934,0.0
78,NaN,96.0,41275.0,41.122303,0.0
988,NaN,63.0,55561.0,227.872071,0.0

In [179]:
#inspecting the median
clv_median = insurance_company["customer_lifetime_value"].median()
print(clv_median)

588174.235

In [181]:
# replacing the missing values with the median and inspecting if there are still any missing values
insurance_company["customer_lifetime_value"] = (
    insurance_company["customer_lifetime_value"].fillna(clv_median)
)
insurance_company["customer_lifetime_value"].isna().sum()

np.int64(0)

In [182]:
# inspecting the data type of this column, just in case
insurance_company["customer_lifetime_value"].dtype

dtype('float64')

In [183]:
#inspecting if there are no missing values in any column, just in case
insurance_company.isna().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
state_original               0
dtype: int64

In [184]:
#identifying the numeric columns
numeric_columns = insurance_company.select_dtypes(
    include="number"
).columns

print(numeric_columns)
print(numeric_columns.dtype)

Index(['customer_lifetime_value', 'income', 'monthly_premium_auto',
       'number_of_open_complaints', 'total_claim_amount'],
      dtype='str')

In [187]:
# checking the data types, just in case
insurance_company[numeric_columns].dtypes

customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
total_claim_amount           float64
dtype: object

In [188]:
# Checking the values and my conclusion is that the decimal values are not meaningful, so, I will convert the values to integers
display(insurance_company[numeric_columns].head())

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
0,588174.235,0.0,1000.0,0.0,2.704934
1,697953.590,0.0,94.0,0.0,1131.464935
2,1288743.170,48767.0,108.0,0.0,566.472247
3,764586.180,0.0,106.0,0.0,529.881344
4,536307.650,36357.0,68.0,0.0,17.269323

In [191]:
object_columns = insurance_company.select_dtypes(
    include="str"
).columns

for column in object_columns:
    print(column)
    print(insurance_company[column].dropna().unique()[:20])

customer
<ArrowStringArray>
['RB50392', 'QZ44356', 'AI49188', 'WW63253', 'GA49547', 'OC83172', 'XZ87318',
 'CF85061', 'DY87989', 'BQ94931', 'SX51350', 'VQ65197', 'DP39365', 'SJ95423',
 'IL66569', 'BW63560', 'FV94802', 'OE15005', 'WC83389', 'FL50705']
Length: 20, dtype: str
state
<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon']
Length: 5, dtype: str
gender
<ArrowStringArray>
['F', 'M']
Length: 2, dtype: str
education
<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor']
Length: 5, dtype: str
policy_type
<ArrowStringArray>
['Personal Auto', 'Corporate Auto', 'Special Auto']
Length: 3, dtype: str
vehicle_class
<ArrowStringArray>
['Four-Door_Car', 'Two-Door_Car', 'SUV', 'Luxury']
Length: 4, dtype: str
state_original
<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali', 'AZ',
 'WA']
Length: 8, dtype: str

In [196]:
# checking if the values are whole numbers
display(
    insurance_company[numeric_columns]
    .mod(1)
    .ne(0)
    .any()
)

customer_lifetime_value       True
income                       False
monthly_premium_auto         False
number_of_open_complaints    False
total_claim_amount            True
dtype: bool

In [197]:
# checking if there are any missing values as using astype(int) gives an error
display(insurance_company[numeric_columns].isna().sum())

customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
total_claim_amount           0
dtype: int64

In [198]:
#inspecting the actual decimal values
for column in ["customer_lifetime_value", "total_claim_amount"]:
    print(f"\n{column}:")
    display(
        insurance_company.loc[
            insurance_company[column].notna()
            & insurance_company[column].mod(1).ne(0),
            [column]
        ].head()
    )

customer_lifetime_value:

   customer_lifetime_value
0               588174.235
1               697953.590
2              1288743.170
3               764586.180
4               536307.650

total_claim_amount:

   total_claim_amount
0            2.704934
1         1131.464935
2          566.472247
3          529.881344
4           17.269323

In [200]:
# rounding the numeric values
insurance_company[numeric_columns] = (
    insurance_company[numeric_columns]
    .round()
    .astype("int64")
)
display(insurance_company[numeric_columns].head())

,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount
0,588174,0,1000,0,3
1,697954,0,94,0,1131
2,1288743,48767,108,0,566
3,764586,0,106,0,530
4,536308,36357,68,0,17

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [130]:
insurance_company.duplicated().any()

np.False_

In [205]:
duplicate_mask = insurance_company.duplicated()

display(duplicate_mask)
print("Number of duplicated rows:", duplicate_mask.sum())

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068    False
1069    False
1070    False
Length: 1071, dtype: bool

Number of duplicated rows: 0

In [207]:
insurance_comp_no_duplicates = insurance_company.drop_duplicates()

print("Rows before:", len(insurance_company))
print("Rows after:", len(insurance_comp_no_duplicates))

Rows before: 1071
Rows after: 1071

In [131]:
if insurance_company.duplicated().any():
    print("Duplicated rows found:")
    display(insurance_company[insurance_company.duplicated(keep=False)])
else:
    print("No duplicated rows found.")

No duplicated rows found.

No duplicates were found so this exercise had no changes to the data.

In [202]:
# saving the cleaned data set to a new cvs file
insurance_company.to_csv("insurance_company_clean.csv", index=False)

In [203]:
# verifying the file location
import os

print(os.getcwd())
print(os.path.exists("insurance_company_clean.csv"))

/Users/sandragoncalves/lab-dw-data-cleaning-and-formatting
True

In [204]:
# confirming if the saved fil can be opened
clean_check = pd.read_csv("insurance_company_clean.csv")

display(clean_check.head())
print(clean_check.shape)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,588174,0,1000,0,Personal Auto,Four-Door_Car,3
1,QZ44356,Arizona,F,Bachelor,697954,0,94,0,Personal Auto,Four-Door_Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door_Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,530
4,GA49547,Washington,M,High School or Below,536308,36357,68,0,Personal Auto,Four-Door_Car,17

(1071, 11)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [ ]:
import pandas as pd


def clean_column_names(insurance_company):
    insurance_company.columns = (insurance_company.columns.str.strip().str.lower().str.replace(" ", "_"))
    return insurance_company.columns.str.strip().str.lower().str.replace(" ", "_")

def remove_empty_rows(insurance_company):
    """Remove rows containing only missing values."""
    return insurance_company.dropna(axis=0, how="all")


def remove_duplicate_rows(insurance_company):
    """Remove duplicated rows."""
    return insurance_company.drop_duplicates()


def clean_open_complaints(insurance_company):
    """Clean the number_of_open_complaints column."""
    # Adapt this logic after inspecting the column's actual values.
    complaints = (
        insurance_company["number_of_open_complaints"]
        .astype("string")
        .str.split("/")
        .str[1]
    )

    insurance_company = insurance_company.copy()
    insurance_company["number_of_open_complaints"] = pd.to_numeric(
        complaints,
        errors="coerce"
    )

    return insurance_company


def main():
    # Load the data here, or pass an already-loaded DataFrame to main().
    url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
    insurance_company = pd.read_csv(url)

    insurance_company = remove_empty_rows(insurance_company)
    insurance_company = clean_open_complaints(insurance_company)
    insurance_company = remove_duplicate_rows(insurance_company)

    return insurance_company


if __name__ == "__main__":
    insurance_company = main()
    display(insurance_company)

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [134]:
insurance_company[["customer_lifetime_value", "total_claim_amount"]].describe()

       customer_lifetime_value  total_claim_amount
count             1.068000e+03         1071.000000
mean              7.936903e+05          404.986909
std               6.434784e+05          293.027260
min               2.004351e+05            0.382107
25%               4.034080e+05          202.157702
50%               5.881742e+05          354.729129
75%               8.962872e+05          532.800000
max               5.816655e+06         2893.239678

In [136]:
claim_75th_percentile = insurance_company["total_claim_amount"].quantile(0.75)
clv_25th_percentile = insurance_company["customer_lifetime_value"].quantile(0.25)
display(claim_75th_percentile)
display(clv_25th_percentile)

np.float64(532.8)

np.float64(403407.995)

In [139]:
selection = (
    (insurance_company["total_claim_amount"] > claim_75th_percentile)
    & (insurance_company["customer_lifetime_value"] < clv_25th_percentile)
)
selection

0       False
1       False
2       False
3       False
4       False
        ...
1066    False
1067    False
1068     True
1069    False
1070    False
Length: 1071, dtype: bool

In [142]:
selected_customers = insurance_company[selection].copy()
selected_customers

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state_original
17,OE15005,California,NaN,College,394524.16,28855.0,101.0,0.0,Personal Auto,SUV,647.442031,Cali
23,TZ98966,Nevada,NaN,Bachelor,245019.10,0.0,73.0,3.0,Corporate Auto,Four-Door_Car,554.376763,Nevada
26,US89481,California,NaN,Bachelor,394637.21,0.0,111.0,0.0,Personal Auto,Four-Door_Car,799.200000,California
38,CM61827,Oregon,NaN,Bachelor,309003.41,0.0,90.0,0.0,Personal Auto,Two-Door_Car,648.000000,Oregon
42,IL19217,California,NaN,Bachelor,393900.64,60021.0,99.0,0.0,Personal Auto,Four-Door_Car,882.871945,California
62,FG63582,Oregon,NaN,Bachelor,333976.49,0.0,94.0,0.0,Personal Auto,Two-Door_Car,863.327324,Oregon
135,MS41162,Arizona,NaN,High School or Below,402296.35,0.0,117.0,0.0,Personal Auto,SUV,975.107098,AZ
140,DS81757,Oregon,M,College,247012.12,0.0,74.0,0.0,Personal Auto,Two-Door_Car,721.242206,Oregon
158,KA61892,Arizona,M,College,387364.70,28142.0,105.0,0.0,Personal Auto,Sports_Car,701.708239,Arizona
160,ND87334,California,M,High School or Below,228759.69,0.0,63.0,0.0,Corporate Auto,Two-Door_Car,679.368378,California
170,TS19868,California,M,College,241313.97,27501.0,63.0,0.0,Personal Auto,Four-Door_Car,542.319401,California
184,AB13432,California,M,Bachelor,373583.81,0.0,110.0,0.0,Personal Auto,SUV,792.000000,California
204,FL34139,California,M,High School or Below,368811.09,0.0,63.0,3.0,Personal Auto,Four-Door_Car,669.682001,California
250,IA63417,Arizona,F,High School or Below,400151.91,19782.0,108.0,0.0,Personal Auto,Two-Door_Car,773.470977,Arizona
269,VZ51506,Arizona,F,High School or Below,359531.29,0.0,103.0,0.0,Corporate Auto,Sports_Car,741.600000,Arizona
279,OH60605,Oregon,F,High School or Below,365253.24,39679.0,92.0,0.0,Personal Auto,Two-Door_Car,641.388616,Oregon
304,RR77985,Oregon,F,Bachelor,288774.23,0.0,80.0,0.0,Personal Auto,Four-Door_Car,676.944023,Oregon
388,JF36291,California,M,College,387364.70,28142.0,105.0,0.0,Personal Auto,Sports_Car,701.708239,California
415,ZF84449,Oregon,F,College,372672.80,0.0,112.0,1.0,Special Auto,Sports_Car,806.400000,Oregon
448,NL93182,Nevada,M,Bachelor,254945.00,0.0,78.0,0.0,Corporate Auto,Four-Door_Car,845.654042,Nevada
450,WE68644,Oregon,F,Bachelor,380392.18,20325.0,100.0,0.0,Personal Auto,Sports_Car,668.293970,Oregon
467,AU96286,Oregon,F,Bachelor,316765.84,0.0,92.0,0.0,Corporate Auto,Four-Door_Car,662.400000,Oregon
486,FY51713,Arizona,F,Bachelor,357076.05,56168.0,88.0,0.0,Personal Auto,Four-Door_Car,614.675906,AZ
500,XN11823,Nevada,F,Bachelor,376446.51,92600.0,94.0,0.0,Corporate Auto,Two-Door_Car,842.437850,Nevada
502,PX17116,Nevada,M,College,362345.42,0.0,111.0,2.0,Corporate Auto,SUV,1171.931170,Nevada
565,XS12556,California,F,College,368309.99,0.0,101.0,0.0,Corporate Auto,Sports_Car,564.466556,California
590,UK41984,Arizona,F,Doctor,383960.61,0.0,112.0,2.0,Personal Auto,SUV,537.600000,Arizona
593,ZK21724,Oregon,F,High School or Below,401654.20,0.0,111.0,0.0,Personal Auto,SUV,799.200000,Oregon
638,DM95829,California,M,College,252395.96,16244.0,68.0,0.0,Personal Auto,Two-Door_Car,623.223617,California
645,JA41698,Nevada,M,Bachelor,309953.80,0.0,102.0,5.0,Corporate Auto,SUV,862.762957,Nevada
669,ED50963,California,F,High School or Below,268886.40,32808.0,68.0,1.0,Personal Auto,Four-Door_Car,541.695658,California
709,NZ15548,Oregon,M,Bachelor,402381.44,41833.0,103.0,0.0,Personal Auto,Four-Door_Car,643.826716,Oregon
788,TE13577,Oregon,F,College,231973.59,0.0,64.0,0.0,Personal Auto,Four-Door_Car,632.715382,Oregon
853,TV25678,Washington,M,College,354090.43,0.0,101.0,0.0,Personal Auto,SUV,727.200000,WA
891,KJ87930,California,F,Bachelor,388650.48,0.0,112.0,0.0,Corporate Auto,SUV,1185.988301,Cali
908,XM72420,Arizona,F,High School or Below,391936.67,66676.0,97.0,0.0,Personal Auto,Four-Door_Car,558.099357,Arizona
949,TD10493,Oregon,F,High School or Below,289873.27,0.0,96.0,4.0,Personal Auto,Four-Door_Car,691.200000,Oregon
1019,OT52034,California,M,Bachelor,386477.68,24204.0,99.0,1.0,Personal Auto,Four-Door_Car,707.303416,Cali
1022,UI73201,California,M,College,366737.50,62375.0,92.0,0.0,Personal Auto,Two-Door_Car,618.630955,Cali
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0.0,Personal Auto,Four-Door_Car,633.600000,Arizona

In [143]:
print(selected_customers.shape)

(40, 12)

In [144]:
print("75th percentile:", claim_75th_percentile)
print("25th percentile:", clv_25th_percentile)

75th percentile: 532.8
25th percentile: 403407.995